train_set: ['public_train', 'public_test']
test_set: []

model: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
num_classes: 1 # only has one class (lettuce)
model_path: 'weights/seg/model_final.pth'
threshold: 0.4

base_lr: 0.0001
max_iter: 3000
steps: [1500]

# post process
up_coeff: 1.6
down_coeff: 0.8