batch_size: 16
img_size: 256
device: cuda:0

img_src: data/classifier_data/single_pill
unlabeled_img_src: data/crop_data
data_dict: data/classifier_data/single_pill.json
num_classes: 107

k_fold: 3 # > 0 to use k-fold

trainer:
  epochs: 16
  backbone: swinv2_small_transformer
  freeze: False
  unfreeze_epoch: 40
  log_step: 100
  eval_step: 9999

  save_path: weights/cls/swinv2_small_new_data_ensemble
  model_name: swinv2_small_transformer

  lr: 0.0001
  cls_lr: 0.001
  
  optim:
    name: 'CosineAnnealingLR'
    milestone: [8]
    gamma: 0.1
    lr_min: 0.00001