pill_image_dir: data/public_test/pill/image
pres_image_dir: data/public_test/prescription/image
pill_pres_map_path: data/public_test/pill_pres_map.json

augment_dir: data/augment

device: 'cuda:0'

label_drugnames_path: results/drugname_label.json
submit_file: results/csv/results.csv

ocr:
  output: results/ocr_output.json

detection:
  model_conf: 0.5
  weight_bbox_only_path: weights/detection/yolov5_weights_without_label.pt
  weight_bbox_label_path: weights/detection/yolov5_weights_with_label.pt

multi_models: True

classifier:
  ensemble: True
  threshold: 0.5
  num_classes: 107
  batch_size: 16
  img_size: 256
  test_img_dir: data/crop_data
  backbone: swinv2_small_transformer
  weight_ensemble_path: weights/cls/swinv2_small_kfold
  weight_path: weights/cls/swinv2_small_transformer.pth
  output: results/csv/classifier_result.csv

classifier_multi_models:
  threshold: 0.5
  num_classes: 107
  batch_size: 16
  num_models: 2
  img_size: [224, 256]
  test_img_dir: data/crop_data
  backbone: [swin_tiny_transformer, swinv2_small_transformer]
  weight_path: [weights/cls/swin_tiny_kfold, weights/cls/swinv2_small_kfold]
  model_weight: [0.4, 0.6]
  output: results/csv/classifier_result.csv

crop:
  crop_img_dir: data/crop_data
  crop_detection_map: results/crop_detection_map.json