pill_image_dir: data/public_test/pill/image
pres_image_dir: data/public_test/prescription/image
device: 'cuda:0'

label_drugnames_path: results/label_drugnames.json
pill_pres_map_path: data/public_test/pill_pres_map.json
submit_file: results/csv/results.csv

ocr:
  output: results/ocr_output.json

detection:
  model_conf: 0.2
  weight_path: detection/yolo/yolov5/runs/train/exp/yolov5_best.pt

classifier:
  threshold: 0.5
  num_classes: 107
  batch_size: 32
  img_size: 224
  test_img_dir: data/crop_data
  weight_path: weights/cls/swin_tiny_cls.pth
  output: results/csv/classifier_result.csv

crop:
  crop_img_dir: data/crop_data
  crop_detection_map: results/crop_detection_map.json