pill_image_dir: data/test
pres_image_dir: data/public_test/prescription/image
device: 'cuda:0'

label_drugnames_path: results/label_drugnames.json
pill_pres_map_path: data/public_test/pill_pres_map.json
submit_file: results/csv/results.csv

ocr:
  output: results/ocr_output.json

detection:
  model_conf: 0.5
  bbox_extend_percent: 0.0
  augment_dir: data/augment
  weight_path: weights/detection/yolov5_best.pt

multi_models: False

classifier:
  ensemble: True
  threshold: 0.5
  num_classes: 107
  batch_size: 16
  img_size: 256
  test_img_dir: data/crop_data
  backbone: swinv2_small_transformer
  weight_ensemble_path: weights/cls/swinv2_small_transformer_ensemble
  weight_path: weights/cls/swinv2_small_transformer.pth
  output: results/csv/classifier_result.csv

classifier_multi_models:
  threshold: 0.5
  num_classes: 107
  batch_size: 16
  num_models: 2
  img_size: [224, 256]
  test_img_dir: data/process_crop_data
  backbone: [swin_tiny_transformer, swinv2_small_transformer]
  weight_path: [weights/cls/swin_tiny_kfold, weights/cls/swinv2_small_kfold]
  model_weight: [0.4, 0.6]
  output: results/csv/classifier_result.csv

crop:
  crop_img_dir: data/crop_data
  crop_detection_map: results/crop_detection_map.json