batch_size: 32
img_size: 224
device: cuda:0

img_src: data/process_data/labeled_pills
unlabeled_img_src: data/crop_data
data_dict: data/process_data/data_single_pills.json
num_classes: 107

k_fold: 0 # > 0 to use k-fold

trainer:
  epochs: 20
  backbone: swin_tiny_transformer
  freeze: False
  unfreeze_epoch: 40
  log_step: 100
  eval_step: 9999

  save_path: weights/cls
  model_name: swin_tiny_transformer

  lr: 0.0001
  cls_lr: 0.001

  optim:
    milestone: [10]
    gamma: 0.1